[project]
name = "lean-scout"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datasets>=4.1.1",
    "pyarrow>=21.0.0",
    "pydantic>=2.11.9",
]
