name: Lint/test and tag on main

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # needed for tagging on main branch

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0  # fetch all history for tagging

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          python-version: "3.13"

      - uses: leanprover/lean-action@v1

      - name: Build Lean project
        run: lake build

      - name: Run tests
        run: ./run_tests

      - name: Tag with Lean version
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: ./.github/actions/tag-lean-version
